-- DDL for table LND_ALLOWANCE
CREATE OR REPLACE TABLE LND_ALLOWANCE (
    ALLOWANCE_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    ALLOWANCE_TYPE VARCHAR(255),
    ALLOWANCE_AMOUNT FLOAT,
    ALLOWANCE_START_DATE DATE,
    ALLOWANCE_END_DATE DATE
);

-- DDL for table LND_TIMESHEET
CREATE OR REPLACE TABLE LND_TIMESHEET (
    TIMESHEET_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    TIMESHEET_TRANSACTION_DATE DATE,
    START_TIME VARCHAR(255),
    END_TIME VARCHAR(255),
    TIMESHEET_TRANSACTION_HOURS FLOAT,
    PAY_PERIOD_ID VARCHAR(255)
);

-- DDL for table LND_TIME_OFF_IN_LIEU
CREATE OR REPLACE TABLE LND_TIME_OFF_IN_LIEU (
    TOIL_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    OVERTIME_DATE DATE,
    TOIL_HOURS_ACCRUED BIGINT,
    TOIL_USAGE_DATE DATE
);

-- DDL for table LND_TAX_RATES
CREATE OR REPLACE TABLE LND_TAX_RATES (
    TAXABLE_INCOME VARCHAR(255),
    TAX_ON_THIS_INCOME VARCHAR(255),
    YEAR VARCHAR(255),
    NOTE VARCHAR(255),
    START_RANGE BIGINT,
    END_RANGE BIGINT,
    DATE_START DATE,
    DATE_END DATE,
    FIXED_TAX BIGINT,
    CUMULATIVE_TAX FLOAT
);

-- DDL for table LND_SUPER_GUARANTEE_RATES_FORMATTED
CREATE OR REPLACE TABLE LND_SUPER_GUARANTEE_RATES_FORMATTED (
    START_PERIOD DATE,
    END_PERIOD DATE,
    SUPER_GUARANTEE_RATE_PERCENTAGE FLOAT
);

-- DDL for table LND_ROSTER
CREATE OR REPLACE TABLE LND_ROSTER (
    ROSTER_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    SHIFT VARCHAR(255),
    HOURS FLOAT,
    WORK_DATE DATE,
    SERVICES VARCHAR(255),
    LOCATION VARCHAR(255),
    PAY_PERIOD_ID VARCHAR(255)
);

-- DDL for table LND_PAY_RATE_ADJUSTMENTS
CREATE OR REPLACE TABLE LND_PAY_RATE_ADJUSTMENTS (
    RATE_TYPE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    RATE_CALCULATION VARCHAR(255)
);

-- DDL for table LND_PAST_PAYSLIPS
CREATE OR REPLACE TABLE LND_PAST_PAYSLIPS (
    EMPLOYEE_ID VARCHAR(255),
    NAME VARCHAR(255),
    GENDER VARCHAR(255),
    LOCATION VARCHAR(255),
    HIRE_DATE DATE,
    STATUS VARCHAR(255),
    PAY_PERIOD VARCHAR(255),
    START_PERIOD TIMESTAMP_NTZ,
    END_PERIOD TIMESTAMP_NTZ,
    TOTAL_EARNINGS VARCHAR(255),
    TAX VARCHAR(255),
    SUPERANNUATION VARCHAR(255),
    ACCRUED_LEAVE FLOAT,
    USED_LEAVE FLOAT,
    BALANCE_LEAVE FLOAT,
    TOTAL_HOURS_WORKED FLOAT,
    NET_PAY VARCHAR(255)
);

-- DDL for table LND_MINIMUM_PAY_RATES
CREATE OR REPLACE TABLE LND_MINIMUM_PAY_RATES (
    PAY_RATE_ID VARCHAR(255),
    EFFECT_FROM DATE,
    EFFECT_TO DATE,
    HOURLY_PERMANENT_RATE FLOAT,
    HOURLY_CASUAL_RATE FLOAT
);

-- DDL for table LND_JUNIOR_PAY_RATES
CREATE OR REPLACE TABLE LND_JUNIOR_PAY_RATES (
    AGE VARCHAR(255),
    PERCENT_OF_ADULT_PAY_RATE FLOAT
);

-- DDL for table LND_EMPLOYEE_LEAVE
CREATE OR REPLACE TABLE LND_EMPLOYEE_LEAVE (
    LEAVE_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    LEAVE_TYPE VARCHAR(255),
    LEAVE_START_DATE DATE,
    LEAVE_END_DATE DATE,
    LEAVE_HOURS FLOAT
);

-- DDL for table LND_EMPLOYEE_DETAILS
CREATE OR REPLACE TABLE LND_EMPLOYEE_DETAILS (
    EMPLOYEE_ID VARCHAR(255),
    EMPLOYEE_FIRST_NAME VARCHAR(255),
    EMPLOYEE_MIDDLE_NAME VARCHAR(255),
    EMPLOYEE_LAST_NAME VARCHAR(255),
    EMPLOYEE_GENDER VARCHAR(255),
    EMPLOYEE_LOCATION VARCHAR(255),
    DATE_OF_BIRTH DATE,
    HIRE_DATE DATE,
    TERMINATION_DATE DATE,
    EMPLOYEE_STATUS VARCHAR(255)
);

-- DDL for table LND_DIM_PAY_PERIOD
CREATE OR REPLACE TABLE LND_DIM_PAY_PERIOD (
    PAY_PERIOD_ID VARCHAR(255),
    PERIOD_START_DATE DATE,
    PERIOD_END_DATE DATE,
    PAYDAY DATE,
    FREQUENCY VARCHAR(255),
    PAY_PERIOD_LABEL VARCHAR(255)
);

-- DDL for table LND_CONTRACT_DETAILS
CREATE OR REPLACE TABLE LND_CONTRACT_DETAILS (
    CONTRACT_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    PAY_RATE FLOAT,
    JOB_TITLE VARCHAR(255),
    PAYMENT_FREQUENCY VARCHAR(255),
    CONTRACT_TYPE VARCHAR(255),
    EMPLOYMENT_TYPE VARCHAR(255),
    CONTRACT_STATUS VARCHAR(255)
);

-- DDL for table LND_COMBINED_HOLIDAYS
CREATE OR REPLACE TABLE LND_COMBINED_HOLIDAYS (
    HOLIDAY_DATE DATE,
    HOLIDAY_NAME VARCHAR(255),
    INFORMATION VARCHAR(1000),
    MORE_INFORMATION VARCHAR(1000),
    JURISDICTION VARCHAR(255),
    DAY_OF_WEEK VARCHAR(255)
);

-- DDL for table LND_BONUS
CREATE OR REPLACE TABLE LND_BONUS (
    BONUS_ID VARCHAR(255),
    EMPLOYEE_ID VARCHAR(255),
    BONUS_TYPE VARCHAR(255),
    BONUS_AMOUNT FLOAT,
    BONUS_DATE DATE
);